import { StyleSheet } from "react-native";

export const Styles = StyleSheet.create({
    container:{
        flex:1,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#ffffff'
    },
    act:{
        position:'relative',
        width:'100%',
        height:'100%',
        alignSelf:'center',
        backgroundColor:'transparent'
    },
    logoimg:{
        backgroundColor:'#ffffff',
        width:250,
        height:250,
    },
    logo:{
        backgroundColor:'#ffffff',
        width:150,
        height:150,
    },
  txtInputContainer:{
        width:'95%',
        marginTop:5,
        alignItems:'center',
        justifyContent:'center',
        elevation:10
    },
    txtInput:{
        width:'95%',
        height:40,
        borderWidth:1,
        textAlign:'center',
        marginTop:10,
        alignSelf:'center',
        borderRadius:20,
        marginBottom:20

    },
    btn:{
        width:'40%'
    },
    touchableTxt:{
      marginTop:10,
      color:'blue',
      fontSize:17
    }
});